user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    # Oculta a versão do Nginx por segurança
    server_tokens off;

    server {
        listen 80 default_server;
        root /app/public;
        index index.php;

        # Regra principal para roteamento do Laravel
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Regra para passar scripts PHP para o PHP-FPM via socket
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Bloqueia acesso a arquivos ocultos
        location ~ /\.ht {
            deny all;
        }
    }
}